# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      #     - uses: actions/checkout@v2
      #     - name: Use Node.js ${{ matrix.node-version }}
      #       uses: actions/setup-node@v2
      #       with:
      #         node-version: ${{ matrix.node-version }}
      #     - run: npm ci
      #     - run: npm run build --if-present
      #     - run: npm test
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
      # - name: Run coverage
      #   # env:
      #   #   REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      #   run: yarn cov:lcov
      # - name: Publish to coveralls.io
      #   uses: coverallsapp/github-action@v1.1.2
      #   with:
      #     github-token: ${{ github.token }}
